travis:
  secure:
    BINSTAR_TOKEN: uZvK94XrYRSEY2skmOr05xRbYJFeoesKvd4u8BQsXa2Dp35VRj2V09WyiqHPTzQBTPjzASznv+K75dDWLItyiK1pFcuSISsH22fuM3LvQuuek/DnOdF+kVyM2FBhndiWuqWK8rhayTzOfqWGv7Ra0RpAbJHd4XbePZASqiYFShXvncxVVHflW4tPcJd8JEzXufm/fOCTOGMKMdHscXC4v2GDhcl+X2ICsifCSA1V7Tz7b10jMWjrdP/DGKWIcozMKfejxxQLrKFx4lRTZJ309fRT3R628KKNfneTA6QQqHksKRqH7F5NmwbjK8MNXEOFo7BH9P6F4EbZEWGtaGNmSsjfO3bl1IxKXZ6PqTJZicoLjUPyutuo5OBf158ONRWIHwGx5PVtuQgsm6Fvx+epMMHL5ar170vjVItjXjUwMc1rU51//3NzyIHbUvL9Iqgqxr4tvIjRq8Dju5gZ9FjLbtHwF8lA5REGFJRwRUHJE7u+GI5exeB7LBtDbCFOGHkF7pzBKz9+bCY65Iuc/dF3KHWtwJ9YHnKA328UXh1dDn9915rPl2NdP4fMFLo1gFpmsavH//hNUunyY+xGYtN8tzZ4TOMCQrSonEb6DlVTYK/AIShtNQUK/Fre+UCG0RmXXEvR0pYtd04pUkZ7mAtzvikBTV03ZvHf15iYG2ELg28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
